#!/bin/bash
echo "Bootstrapping latest Kubernetes 1.36 version"
echo "Starting containerd installation for Ubuntu/Debian..."
# Configure kernel modules
cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
overlay
br_netfilter
EOF
sudo modprobe overlay
sudo modprobe br_netfilter
# Configure sysctl parameters
cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
EOF
sudo sysctl --system
# Install containerd
sudo apt-get update
sudo apt-get -y install containerd
# Generate containerd configuration
sudo mkdir -p /etc/containerd
# Configure systemd cgroup driver and sandbox pause image default
containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' | sed 's/pause:3.8/pause:3.10.1/' | sudo tee /etc/containerd/config.toml

# Start and enable containerd
sudo systemctl restart containerd
sudo systemctl enable containerd
echo "Containerd installation complete!"
sudo systemctl status containerd --no-pager

# Disable swapfile for kubelet
sudo swapoff -a
sudo sed -i '/\/swap.img/s/^/#/' /etc/fstab

# Install latest version of kubeadm, kubelet, kubectl
sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl gpg
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.36/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl
sudo systemctl enable --now kubelet

sudo echo "serverTLSBootstrap: true" >> /var/lib/kubelet/config.yaml
sudo systemctl daemon-reload
sudo systemctl restart kubelet

# Prevent laptop from going to sleep when lid is closed (this is a server)
cat <<EOF >> /etc/systemd/logind.conf
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore
HandleLidSwitchDocked=ignore
EOF

sudo systemctl daemon-reload
sudo systemctl restart systemd-logind

echo "bootstrap conpleted! next step would be to use the kubeadm join command generated by the controlplane init"